# Generated by Django 4.1.7 on 2023-03-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_applicabletaxdetails'),
        ('account', '0002_remove_userprofile_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_of_property', to='configuration.property'),
        ),
    ]
