# Generated by Django 4.1.7 on 2023-02-23 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=128, unique=True)),
                ('occupancy', models.IntegerField(default=2)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('is_operational', models.BooleanField(default=True)),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.property')),
                ('room_catgory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.roomcategory')),
            ],
        ),
        migrations.CreateModel(
            name='RoomRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(max_length=128, unique=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.property')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.room')),
            ],
        ),
    ]
