# Generated by Django 4.1.7 on 2023-02-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_room_roomrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='short_name',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
