# Generated by Django 4.1.7 on 2023-02-24 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_room_room_no_alter_room_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomrate',
            name='room_no',
        ),
    ]
