# Generated by Django 4.1.7 on 2023-02-28 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_roomrate_created_at_roomrate_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_operational',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='configuration.property'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='configuration.roomcategory'),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_rates', to='configuration.property'),
        ),
        migrations.AlterField(
            model_name='roomrate',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_rates', to='configuration.room'),
        ),
    ]
