# Generated by Django 4.1.7 on 2023-03-02 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('configuration', '0008_property_is_operational_alter_room_property_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicableTaxDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lower_limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('upper_limit', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cgst_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sgst_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('service_tax_percentage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_applicable', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicable_tax_details', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
