# Generated by Django 4.1.7 on 2023-02-24 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configuration', '0003_property_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_no', models.CharField(max_length=128)),
                ('lead_guest_name', models.CharField(blank=True, max_length=128)),
                ('reservation_for', models.CharField(max_length=128)),
                ('reservation_from', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=1024)),
                ('contact_no', models.CharField(blank=True, max_length=12, null=True)),
                ('remarks', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('property', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.property')),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='operation.reservationdetails')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.room')),
            ],
        ),
    ]
