# Generated by Django 4.1.7 on 2023-02-24 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0007_roomrate_created_at_roomrate_created_by_and_more'),
        ('operation', '0002_reservationdetails_checkin_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetails',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='configuration.property'),
        ),
    ]
