# Generated by Django 4.1.7 on 2023-02-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0003_reservationdetails_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationdetails',
            name='reservation_no',
            field=models.CharField(max_length=15),
        ),
    ]
