# Generated by Django 4.1.7 on 2023-02-28 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_alter_reservationroomdetails_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetails',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservationdetails',
            name='total_room_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.CreateModel(
            name='GuestCheckInCheckOutDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField()),
                ('checkout_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=2048, null=True)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guest_checkin_check_out', to='operation.reservationdetails')),
            ],
        ),
    ]
