# Generated by Django 4.1.7 on 2023-03-01 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0007_guestcheckincheckoutdetails_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousservicechargedetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='miscellaneousservicechargedetails',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miscellaneous_service_charge', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='miscellaneousservicechargedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
