# Generated by Django 4.1.7 on 2023-03-01 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0008_miscellaneousservicechargedetails_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousservicechargedetails',
            name='service_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
