# Generated by Django 4.1.7 on 2023-03-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0009_miscellaneousservicechargedetails_service_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miscellaneousservicechargedetails',
            name='service_date',
            field=models.DateField(),
        ),
    ]
