# Generated by Django 4.1.7 on 2023-03-01 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0010_alter_miscellaneousservicechargedetails_service_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationdetails',
            name='is_payment_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='guestcheckincheckoutdetails',
            name='no_adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='guestcheckincheckoutdetails',
            name='no_child',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ReservationBillDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(max_length=12)),
                ('total_room_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=8)),
                ('service_date', models.DateField()),
                ('remarks', models.CharField(blank=True, max_length=2048, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_bill_details', to=settings.AUTH_USER_MODEL)),
                ('reservation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservation_bill_details', to='operation.reservationdetails')),
            ],
        ),
    ]
