# Generated by Django 4.1.7 on 2023-03-01 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0011_reservationdetails_is_payment_received_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miscellaneousservicechargedetails',
            old_name='service_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='reservationbilldetails',
            old_name='service_date',
            new_name='end_date',
        ),
        migrations.AddField(
            model_name='reservationbilldetails',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
