# Generated by Django 4.1.7 on 2023-03-01 07:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_rename_service_date_miscellaneousservicechargedetails_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservationbilldetails',
            old_name='cost',
            new_name='sgst_rate',
        ),
        migrations.RemoveField(
            model_name='reservationbilldetails',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='reservationbilldetails',
            name='start_date',
        ),
        migrations.AddField(
            model_name='miscellaneousservicechargedetails',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationbilldetails',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservationbilldetails',
            name='total_service_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
