# Generated by Django 4.1.7 on 2023-03-01 08:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_rename_cost_reservationbilldetails_sgst_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservationdetails',
            name='refund',
        ),
        migrations.AddField(
            model_name='reservationbilldetails',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservationbilldetails',
            name='other_cess_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservationbilldetails',
            name='refund',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
