# Generated by Django 4.1.7 on 2023-03-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0014_remove_reservationdetails_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservationbilldetails',
            name='other_cess_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='reservationbilldetails',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='reservationbilldetails',
            name='total_room_cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='reservationbilldetails',
            name='total_service_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
