# Generated by Django 4.1.7 on 2023-03-02 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0017_alter_reservationdetails_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneousservicechargedetails',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='miscellaneousservicechargedetails',
            name='other_cess_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='miscellaneousservicechargedetails',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservationroomdetails',
            name='cgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservationroomdetails',
            name='other_cess_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='reservationroomdetails',
            name='sgst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
