# Generated by Django 4.1.7 on 2023-03-03 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_miscellaneousservicechargedetails_cgst_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroomdetails',
            name='no_adult',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservationroomdetails',
            name='no_child',
            field=models.IntegerField(default=0),
        ),
    ]
