# Generated by Django 4.1.7 on 2023-03-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0019_reservationroomdetails_no_adult_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationroomdetails',
            name='is_checkin',
            field=models.BooleanField(default=False),
        ),
    ]
